### ISSUE TITLE
Updated template scenes and prefabs

### ISSUE THREAD

**Issue by anonOstrich** [Ohtu-ATKYTP/atkytp2019-game#160]

**Comment by tonitomaatti** [comment]
- FOUNDATION TEMPLATE:
	- Kamerasta ei pitäisi tarvia välittää, kun haluaa tehdä uuden minipelin.

	- Joku canvas tai template paikka johon tietää että voi tehä omat jutut. Sama koko kuin koko ruudulla?

	- Templatessa layerit, että omat jutu menevät infoUI:n alle jos osuvat muuten samaan kohtaan.

	- Päätettiin että yritetään tehdä jutut UI-tyyppisellä renderöinnillä.
